# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook_local.yml

- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true
  vars_files:
    - "vars.yml"
  roles:
    - geerlingguy.firewall
    - geerlingguy.java
    - apolloclark.zookeeper
    - apolloclark.kafka
    - apolloclark.elasticsearch
    - apolloclark.logstash
    - apolloclark.kibana
    - apolloclark.auditbeat
    - apolloclark.filebeat
    - apolloclark.packetbeat
    - apolloclark.metricbeat
    - apolloclark.heartbeat
    - apolloclark.osquery
    - apolloclark.crontab
